{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8spacket.name" . }}-role
rules:
  - apiGroups:
    - ""
    resources:
    - "pods"
    - "services"
    - "nodes"
    verbs:
    - "get"
    - "watch"
    - "list"
{{- end }}
