apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8spacket.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8spacket.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.k8sPacket.tcp.listener.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "k8spacket.selectorLabels" . | nindent 4 }}
